### ISSUE TITLE
[Missing event] onReceiveBannerAd

### ISSUE THREAD

**Issue by davidvazteixeira** [sunnycupertino/cordova-plugin-admob-simple#11]
Hi,

There ins't an event 'onReceiveBannerAd', the duo of 'onReceiveInterstitialAd'.

Do I have to use the event onReceiveAd?

I am interrested in the same "preload" behavior of the interstitial.

Maybe the solution is something like calling "window.plugins.AdMob.requestInterstitialAd();", but for banner.

Thanks in advanced!

**Comment by sunnycupertino** [comment]
Currently there is no way to do that unless you go in and modify the .java file, and yes use the onReceiveAd.
