### ISSUE TITLE
window.plugins.admob always undefined

### ISSUE THREAD

**Issue by s4u2017** [sunnycupertino/cordova-plugin-admob-simple#17]
window.plugins.AdMob always return undefined

function initAd(){
        if ( window.plugins && window.plugins.AdMob ) {

Please Help

**Comment by sunnycupertino** [comment]
This usually happens if you call initAd() before cordova is ready. 

Call initAd() from onDeviceReady()....

**Comment by s4u2017** [comment]
I call it inside the function onDeviceReady() but still retun undefined 
Please help

**Comment by sunnycupertino** [comment]
Is it window.plugins or window.plugins.AdMob that is undefined? If it is the first one, then Cordova is not initialized properly, if the second, then try uninstalling the plugin and reinstalling.

**Comment by s4u2017** [comment]
both of them , i'm working on it from 4 days ago without solution ,

i installed the app many times , and the error not solved

**Comment by sunnycupertino** [comment]
Did you try recreating the whole project? Can you get the basic project to work without any changes or plugins first?

**Comment by s4u2017** [comment]
yes i created a empty project using phonegap desktop app , and i installed the app via nodejs commande nmp but not working ,

i worked with other admob plugins and always return me undefined.

can you send  me a simple project working with cordova-plugin-admob-simple  please?

**Comment by sunnycupertino** [comment]
Sure, give me a few hours, I will do it later today.

**Comment by s4u2017** [comment]
Thanks a lot bro 👍  this is my email : s4u.opensource@gmail.com

**Comment by sunnycupertino** [comment]
Is this for Android or IOS?

**Comment by s4u2017** [comment]
For Android please

**Comment by sunnycupertino** [comment]
Ok I sent it to your email, remember to put in your own admob id's in the \platforms\android\assets\www\js\index.js file.

If anyone else wants a copy you can get it from here https://drive.google.com/open?id=0B_etFuFoOzoNVmxpeXZzbWx3d3M

**Comment by s4u2017** [comment]
Thanks bro ;)

**Comment by sunnycupertino** [comment]
Welcome.

**Comment by s4u2017** [comment]
hello bro,

the same problem , not working and always return undefined :(

**Comment by sunnycupertino** [comment]
Did you put in your admob id? I ran that code myself and it worked. All i did was comment out the id before sending it to you.

**Comment by s4u2017** [comment]
i copied your code in www/index.html and it's not working

**Comment by s4u2017** [comment]
i copied the code from hallo2\plugins\cordova-plugin-admob-simple\test\index.html and i past it on www/index.html and not working

i run the same project you sent me

**Comment by sunnycupertino** [comment]
Of course not.

**Comment by s4u2017** [comment]
so what i should do ?

**Comment by s4u2017** [comment]
what i should do ?

2017-03-30 21:19 GMT+01:00 Sunny Cupertino <notifications@github.com>:

**Comment by rlam3** [comment]
@s4u2017 any resolution? I'm facing a similar issue.
