### ISSUE TITLE
Admob data in Firebase Analytics Console

### ISSUE THREAD

**Issue by amokrunner** [sunnycupertino/cordova-plugin-admob-simple#18]
Can anybody confirm whether the Admob impression/click data from this plugin appears in the Firebase Analytics Console (and which Firebase plugin are you using)?
Thanks!

**Comment by sunnycupertino** [comment]
You should follow the top 2 steps from here
https://firebase.google.com/docs/admob/android/start/

So do up to "compile 'com.google.firebase:firebase-ads:11.0.1'"

**Comment by amokrunner** [comment]
@sunnycupertino : have you actually done this? It builds fine but I still do not see the AdMob data in Firebase Analytics.
