### ISSUE TITLE
Resetting percentage

### ISSUE THREAD

**Issue by Blanketsniffer** [sunnycupertino/cordova-plugin-admob-simple#19]
hey man how are you doing my app id is com.blanketsniffer.hallom can you please check it on your server if you set the ad share from 2% to much higher. i genuinely  know its not 2% right now.

**Comment by sunnycupertino** [comment]
It is 2%. Our code is working flawlessly. We can see your app has only had 10-50 installs. How many ad impressions do you expect, and how many do you see in your admob account? It's more likely you have an implementation issue.

**Comment by Blanketsniffer** [comment]
huh. I guess I was lucky at the begining then. you can close it.
