### ISSUE TITLE
Show and hide Ads for specific pages

### ISSUE THREAD

**Issue by DipakMahapurkar** [sunnycupertino/cordova-plugin-admob-simple#2]
Hello @sunnycupertino,
I want to hide ads for some pages like login page, introduction page, about us page and also show ads for specific pages in ionic framework.
How to resolve this issue.
Thank You!!

**Comment by sunnycupertino** [comment]
Hi

Assuming you added the relevant functions to the javascript as explained in the readme, and called initAd() from onDeviceReady(), then:

showBannerFunc() - to show ads

window.plugins.AdMob.destroyBannerView(); - to hide ads

Call the above on the relevant page load events.

**Comment by DipakMahapurkar** [comment]
Thank for reply, I used those function in my code after loading the controller i will call window.plugins.AdMob.destroyBannerView();  then return back to previous view it will doesn't show me banner.

**Comment by sunnycupertino** [comment]
When you return back to the previous view do you call showBannerFunc() and then wait for it to load?

**Comment by sunnycupertino** [comment]
So did it work? Can I close this issue?

**Comment by stillatmylinux** [comment]
I'm having different results on my local dev env where it works well than I am with my staging env where it doesn't, so I'll do more testing and let you know what was different.
