### ISSUE TITLE
Android shows just black space

### ISSUE THREAD

**Issue by wo-github** [sunnycupertino/cordova-plugin-admob-simple#20]
Hello,
we use this plugin to show ads. With ios it works, but on android there are problems.
If we set in the config isTesting = true, the testbanner is shown. But if we change to isTesting = false, there is just a black space, instead of the banner

With isTesting = false
![livebanner](https://user-images.githubusercontent.com/25742551/28256555-e7dfeb26-6ac3-11e7-8476-6a745c3fca52.png)

With isTesting = true
![testbanner](https://user-images.githubusercontent.com/25742551/28256558-eb0aa656-6ac3-11e7-81a7-0fac73c47888.png)

Our config:
window.plugins.AdMob.setOptions( {
        publisherId: admobid.banner,
        interstitialAdId: admobid.interstitial,
        adSize: window.plugins.AdMob.AD_SIZE.SMART_BANNER,
        bannerAtTop: false,
        overlap: false,
        offsetTopBar: false,
        isTesting: true,
        autoShow: false
    });

call the banner:
window.plugins.AdMob.createBannerView();

**Comment by sunnycupertino** [comment]
This can happen if the ad ID is still new. Admob doesnt serve ads sometimes for 24 hours. Please let us know if it still happens after that time.

**Comment by wo-github** [comment]
No this doesn`t work.
If I add this event listener document.addEventListener('onFailedToReceiveAd', function(data){});
there is this internal error.

![error](https://user-images.githubusercontent.com/25742551/28304716-2be1150e-6b99-11e7-89e4-e2f701e11d26.png)

That description isn`t helpfull.

**Comment by sunnycupertino** [comment]
If the test ads work, then this is a problem from the admob end. Admob does not 'trust' your app for some reason.

Can you tell us the app id?

Do you run this in the emulator or on a real device?

If it's on a real device, is the apk signed?

**Comment by wo-github** [comment]
This happens after install the app on a real device with "phonegap run android".
What is the role of the AppId?

**Comment by sunnycupertino** [comment]
Is the app signed?

The appid might be already used by someone else. If you tell me I can check.

**Comment by wo-github** [comment]
This helps, thank you. You have to build a signed app. It doens`t work with "phonegap run android".
It would be nice, if there is a error message, with this information.

**Comment by sunnycupertino** [comment]
You're welcome, glad to hear it.
