### ISSUE TITLE
capping doesn't work

### ISSUE THREAD

**Issue by Blanketsniffer** [sunnycupertino/cordova-plugin-admob-simple#23]
I love the plugin but for last 15 days plugin shows ads after I close the app and doesn't respect capping number that I set on AdMob. what may be the cause for this?

**Comment by sunnycupertino** [comment]
How are you setting the frequency capping, and where?

**Comment by sunnycupertino** [comment]
And what do you mean it shows ads after you close the app. What kind of ads? Interstitial?

**Comment by wo-github** [comment]
Same problem here, with phonegap. The FC doesn`t work evertime on iOS with an interstitial banner. The interstitial should be show 1 time per day, but sometimes you see the interstitial after every klick. The IP adress doesn`t change in this time.
autoShow is false in the config
We call the interstitial with window.plugins.AdMob.showInterstitialAd(); everytime we change the page.
I expect, that I can call the interstitial everytime and the FC is managed by the ad-network and not by the app.

**Comment by sunnycupertino** [comment]
The frequency cap is managed by the admob servers, not our app. What I would suggest is that you set a cookie on the phone that determines the date and if an interstitial was shown yet, and if it was shown, do not call showInterstitialAd().
