### ISSUE TITLE
Admob code

### ISSUE THREAD

**Issue by YounesZaidi-IT** [sunnycupertino/cordova-plugin-admob-simple#24]
you say you don't load any ads from serveur i'm find this link in your plugin 
in Admob.Java  line 728
http://sample-env-1.ydy8pxiph3.us-west-2.elasticbeanstalk.com/

you can explain pleas  ? so this plugin is not free ?

**Comment by sunnycupertino** [comment]
2% of the ads use our ad code, which comes from that server. It says that on our instructions page.

**Comment by YounesZaidi-IT** [comment]
so this is plugin cordova-admob-pro ?? because i see is the same code and same thing 2% sharing ads

**Comment by sunnycupertino** [comment]
No it is not the same. Our code is completely open source. The plugin you mentioned is different.
