### ISSUE TITLE
 How to know your Google Mobile Ads SDK version

### ISSUE THREAD

**Issue by CodedCloudz** [sunnycupertino/cordova-plugin-admob-simple#27]
Hi,
I just received the below notice in my Admob dashboard:

Starting January 23, 2018, we will no longer be supporting Android and iOS Google Mobile Ads SDKs lower than version 7.0.0. To continue serving ads from AdMob after this date, please upgrade to the latest Google Mobile Ads SDK.

Please how can I check and detect the Google Mobile Ads SDK version in this plugin.
I am using the below versions in all my apps:
cordova-admob-sdklibs version = 2.1.4

cordova-plugin-admob-simple = 3.1.8

Hope to hear from you soon

**Comment by sunnycupertino** [comment]
Oh no problem, our plugin uses a much higher version than this.

https://github.com/sunnycupertino/cordova-admob-sdklibs
