### ISSUE TITLE
Meteor 1.6.1 GenericAdPlugin: Invalid action passed: createBannerView

### ISSUE THREAD

**Issue by lugaru90** [sunnycupertino/cordova-plugin-admob-simple#29]
Hey,

so im using this plugin in meteor 1.6.1. On Client startup, Admob is initialized and events are registered. By clicking a button, i'm calling: window.plugins.AdMob.createBannerView(); 

This Results in the following console output:
W/GenericAdPlugin: Invalid action passed: createBannerView

Same happens for functions like showAd() etc. Same happens by calling the commands over the console.

Any ideas? Thanks :)

**Comment by sunnycupertino** [comment]
Sounds like meteor is not initializing the java side functions. We are not meteor experts, don't know about it, sorry.
