### ISSUE TITLE
Google Consent SDK

### ISSUE THREAD

**Issue by yanbaha** [sunnycupertino/cordova-plugin-admob-simple#32]
I am using this plugin in my apps. Now I am asking if it is necessary to install Google Consent SDK because so many dveloppers had their Admob accounts blocked.

**Comment by sunnycupertino** [comment]
Why did the developers have their accounts blocked? Because they didnt ask for consent?

**Comment by yanbaha** [comment]
I am not sure really.
but so many of them are blocked just after implementing this new law.
so I just want to know if I have to do any changes and weather this plugin provide any solution or I have to disable ads.
I have an adsense account linked so I am afraid to lose everything.

**Comment by sunnycupertino** [comment]
Our plugin does not have a solution right now. Do you have any example of apps that were blocked? Possibly they were breaking the google terms of service to begin with, and they only spotted it after it was updated. Google has a consent sdk, you could use this https://github.com/googleads/googleads-consent-sdk-android
