### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by huymc** [sunnycupertino/cordova-plugin-admob-simple#33]
I tested your plugin with a sample app generated by cordova. However, both banner and interstitial ads don't show ( i used my real ad id) . Can you help?

**Comment by sunnycupertino** [comment]
Hi. It can take time for google to activate it for the new app, and also if they know you are on a dev system they wont show ads. For example if you run an unsigned app. Wait a day and let me know.

**Comment by huymc** [comment]
This is the[ url](https://www.megaupload.us/s4~i?e46bfce43c58f7d0014b77e824030005) to download my project. Can you help check it out?

**Comment by sunnycupertino** [comment]
No I won't run the app for security reasons. If you set istesting to true and you see ads it should be fine. Do you see ads when true?

**Comment by huymc** [comment]
Hi. It worked fine today. Thank you!

**Comment by sunnycupertino** [comment]
Great to hear. Yeah maybe they have some review process.
