### ISSUE TITLE
no erros messages, and no banners!?!?

### ISSUE THREAD

**Issue by seniDEac** [sunnycupertino/cordova-plugin-admob-simple#37]
Hi there! and thanks for your work!! 
but hey, did't not work here.

I used cordova 8.0.0, 
and Everything was nice and easy just like your tutor,  no errors at all..
(plus I get my credetiasl from google...  )

still, in the end.. no banners... 
NOTE: I access the device from my chrome "remote devices" tool, and  the same: no errors...
NOTE2: to be sure, I use the very same credentials from the exemple  video, I get  message errors!!!
that seems the system is working!! 
here the error message, for exemple credentials:

/getconfig/pubsettin…otname=7680949608:1 Failed to load resource: the server responded with a status of 400 ()
sdk-core-v40-impl.js:209 GET https://googleads.g.doubleclick.net/getconfig/pubsetting?app_name=helo.word&client=ca-app-pub-4789158063632032&slotname=7680949608 400

    *** remenber, whith my credentials,,, no erros!!! :)

can you advise-me?

thanks :D

**Comment by sunnycupertino** [comment]
With isTesting set to true do you see ads? Google wont serve ads usually to test devices or unsigned apps.

**Comment by seniDEac** [comment]
I tested by "false" and "true", no changes....
same errors, same places...

**Comment by seniDEac** [comment]
Hi there again!
I put a copy of my tests on    "https://github.com/seniDEac/AdMobTEST "

maybe it can help some way... and  improve this admob in the future..

tkks!

**Comment by Neumann-Valle** [comment]
it happens to me too.. using phonegap, even used ads ca-app-pub-3940256099942544/6300978111 to see if that was the problem..

I guess this project has been left alone..

anyone know any other current project out there in the wild?

**Comment by sunnycupertino** [comment]
Admob changed a bit, you need to add your admob id to the manifest now. We updated the readme, please check it.
