### ISSUE TITLE
Could not find com.google.android.gms:play-services-basement:12.0.1.

### ISSUE THREAD

**Issue by voduchien** [sunnycupertino/cordova-plugin-admob-simple#39]
I cannot build app
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-basement:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-base:11.0.4
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-base:11.0.4 > com.google.android.gms:play-services-tasks:11.0.4
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-ads-lite:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-basement:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-gass:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-ads-license:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command finished with error code 1: cmd /s /c ""c:\users\hienvd\documents\visual studio 2017\Projects\BlankCordovaApp3\BlankCordovaApp3\platforms\android\gradlew.bat" cdvBuildRelease -b "c:\users\hienvd\documents\visual studio 2017\Projects\BlankCordovaApp3\BlankCordovaApp3\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

1>MSBUILD : cordova-build error : Error: cmd: Command failed with exit code 1 Error output:
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.

1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-basement:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-base:11.0.4
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-base:11.0.4 > com.google.android.gms:play-services-tasks:11.0.4
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-ads-lite:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-lite/12.0.1/play-services-ads-lite-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-basement:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/12.0.1/play-services-basement-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-gass:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gass/12.0.1/play-services-gass-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error :  > Could not find com.google.android.gms:play-services-ads-license:12.0.1.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-license/12.0.1/play-services-ads-license-12.0.1.aar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.google.android.gms:play-services-ads:12.0.1
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M

**Comment by sunnycupertino** [comment]
You have to launch the sdk manager and download and install the following files located under "extras" (if you don't have them already): Android support repository, Google play services, Google repository.
