### ISSUE TITLE
not error but not show Ads

### ISSUE THREAD

**Issue by bachdienquan** [sunnycupertino/cordova-plugin-admob-simple#41]
not error but not show Ads. i have add my admob id to the manifest

**Comment by sunnycupertino** [comment]
Does it work with test ads, eg. isTesting=true in the javascript?

**Comment by bachdienquan** [comment]
Thanks @sunnycupertino . Test Ads show. beside that autoShow: false but interstitial ad auto show when device ready. i don't call window.plugins.AdMob.showInterstitialAd();

**Comment by sunnycupertino** [comment]
If test ads show then the problem is likely because your app is not signed, or you run it through an emulator, and adwords won't show ads in that case. Try signing your app and run it that way.

**Comment by Amiga4ever** [comment]
I have similiar issue. No ads even in test mode. Plugin installed, all set to .js file and still receiving error: 'Uncaught TypeError: Cannot read property 'AdMob' of undefined'

My spec:
-Android Studio 3.2.1
-targetSdkVersion="26", 
-Cordova 8.1.2 

***UPDATE***
Finally I've managed to run it.

**Comment by sunnycupertino** [comment]
> I have similiar issue. No ads even in test mode. Plugin installed, all set to .js file and still receiving error: 'Uncaught TypeError: Cannot read property 'AdMob' of undefined'
> 
> My spec:
> -Android Studio 3.2.1
> -targetSdkVersion="26",
> -Cordova 8.1.2
> 
> _**UPDATE**_
> Finally I've managed to run it.
