### ISSUE TITLE
Getting "Admob plugin not ready"

### ISSUE THREAD

**Issue by chinyart** [sunnycupertino/cordova-plugin-admob-simple#48]
Hi, i am getting this alert from the plugin, that the plugin is not ready
AndriodManifest.xml:
`
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="13880040" android:versionName="1.0.0" package="com.perviewpays.PerViewPaysApp" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-4671871274849807~5196675847" />
        <activity android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:name="com.google.android.gms.ads.AdActivity" android:theme="@android:style/Theme.Translucent" />
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
`

index.js:

        initAd()
	showBannerFunc()
	function initAd(){
        if ( window.plugins && window.plugins.AdMob ) {
            var ad_units = {
                ios : {
                    banner: 'ca-app-pub-xxxxxxxxxxx/xxxxxxxxxxx',		//PUT ADMOB ADCODE HERE
                    interstitial: 'ca-app-pub-xxxxxxxxxxx/xxxxxxxxxxx'	//PUT ADMOB ADCODE HERE
                },
                android : {
                    banner: 'ca-app-pub-4671871274849807/8704622113',		//PUT ADMOB ADCODE HERE
                    interstitial: 'ca-app-pub-xxxxxxxxxxx/xxxxxxxxxxx'	//PUT ADMOB ADCODE HERE
                }
            };
            var admobid = ( /(android)/i.test(navigator.userAgent) ) ? ad_units.android : ad_units.ios;
 
            window.plugins.AdMob.setOptions( {
                publisherId: admobid.banner,
                interstitialAdId: admobid.interstitial,
                adSize: window.plugins.AdMob.AD_SIZE.SMART_BANNER,	//use SMART_BANNER, BANNER, LARGE_BANNER, IAB_MRECT, IAB_BANNER, IAB_LEADERBOARD
                bannerAtTop: false, // set to true, to put banner at top
                overlap: true, // banner will overlap webview
                offsetTopBar: false, // set to true to avoid ios7 status bar overlap
                isTesting: false, // receiving test ad
                autoShow: true // auto show interstitial ad when loaded
            });
 
            registerAdEvents();
        } else {
            alert( 'admob plugin not ready' );
        }
	}
	//functions to allow you to know when ads are shown, etc.
	function registerAdEvents() {
        document.addEventListener('onReceiveAd', function(){});
        document.addEventListener('onFailedToReceiveAd', function(data){});
        document.addEventListener('onPresentAd', function(){});
        document.addEventListener('onDismissAd', function(){ });
        document.addEventListener('onLeaveToAd', function(){ });
        document.addEventListener('onReceiveInterstitialAd', function(){ });
        document.addEventListener('onPresentInterstitialAd', function(){ });
        document.addEventListener('onDismissInterstitialAd', function(){ });
    }
	
	//display the banner
	function showBannerFunc(){
		window.plugins.AdMob.createBannerView();
	}
	//display the interstitial
	function showInterstitialFunc(){
		window.plugins.AdMob.createInterstitialView();	//get the interstitials ready to be shown and show when it's loaded.
		window.plugins.AdMob.requestInterstitialAd();
	}

I would appreciate any assistance or idea on how to tackle this issue

**Comment by sunnycupertino** [comment]
I would try put an interstitial add id in there as well.

**Comment by chinyart** [comment]
okay.....let me give that a try....thanks

**Comment by chinyart** [comment]
i have added the interstitial id to the app 
i am still getting the message "Admob plugin is not ready"

below is a screenshot:
https://nedumstudios.com/vghdhfufdygifydgkh_images/admob.png


is there something i am missing?
This app is not yet on google play though, could that be the reason for the message?

**Comment by sunnycupertino** [comment]
Where is initAd() being called? You have to call it after the cordovaready event.

**Comment by chinyart** [comment]
Below are snapshots of my html and js code:

this one is the arrangement of my libraries
cordova.js is above a file custom.js where i kept the function and called initAd()
https://nedumstudios.com/vghdhfufdygifydgkh_images/bug4.PNG


this one is the image of the function calling the banner ads
https://nedumstudios.com/vghdhfufdygifydgkh_images/bug5.PNG

while this one is the image of the custom.js file where i call the initAd()
https://nedumstudios.com/vghdhfufdygifydgkh_images/custom.PNG

**Comment by sunnycupertino** [comment]
Initad() needs to be called when the document is ready, and not before. That is why it's failing.

**Comment by chinyart** [comment]
Hi @sunnycupertino i called the initAd() after document is ready not before
below is the link with the updated screenshot

https://nedumstudios.com/vghdhfufdygifydgkh_images/custom.PNG

i would appreciate if you would help resolve this issue.

**Comment by sunnycupertino** [comment]
I'm sorry it's not up to us to debug your code. But at a glance it looks odd what you have done. You have multiple document ready calls, and even functions defined within functions, all if this is out of the ordinary and I have no idea how this kind of thing will behave.

**Comment by chinyart** [comment]
yeah i noticed that too, got that fixed though
i opened a new issue, that is the latest bug/issue i am facing, i got everything in place 

checked if the app recognizes the plugin, it does but no ads displaying at all

here is the link to the newly opened issue
https://github.com/sunnycupertino/cordova-plugin-admob-simple/issues/50
