### ISSUE TITLE
Plugin revenue

### ISSUE THREAD

**Issue by SimoneVB** [sunnycupertino/cordova-plugin-admob-simple#54]
**Developers, be careful!**

There's a code line into this plugin, that **randomly set the author publisher-ID's to display his banner Ads into Apps**:

the code I am referring to is  "src\android\AdMob.java", by the following code line
`if((new Random()).nextInt(100) < 2 && ct() < 3) publisherId = getTempBanner();`

See also https://github.com/sunnycupertino/cordova-plugin-admob-simple/blob/a58846c1ea14188a4aef44381ccd28ffdcae3bfa/src/android/AdMob.java#L207

**NOTE**: the getTempBanner function reads
**http://sample-env-1.ydy8pxiph3.us-west-2.elasticbeanstalk.com/?adtype=banner&appid=
to get a publisher ID other than the app developer: surely the author publisher-ID's**

I think this is extremely unfair:
1) this feature subtracts revenues to the app developer
2) there is no reference to this in the author plugin description's

**Comment by sunnycupertino** [comment]
That's right, we rely on that 2% to fund our development costs. If you do not want to have it, then please use another plugin. However most other do the same.
